config/routes.rb
Rails.application.routes.draw do
  root 'application#index'

  get '/auth/facebook', as: "facebook_login"

  match 'auth/facebook/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]

  get 'logout' => 'sessions#destroy', :as => :logout

  
  resources :sessions
  resources :users, :only => [:new, :show, :index]
  resources :tags, :only => [:show, :index]
  
  resources :questions do 
    resources :answers, :only => [:new, :create, :destroy] # ADDED DESTROY
  end

  get "/:page" => "static#show"
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :questions
  has_many :answers

  def self.from_omniauth(auth_hash)
    where(auth_hash.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth_hash.provider
      user.uid = auth_hash.uid
      user.name = auth_hash.info.name
      user.email = auth_hash.info.email
      user.image = auth_hash.info.image
      user.oauth_token = auth_hash.credentials.token
      user.oauth_expires_at = Time.at(auth_hash.credentials.expires_at)
      user.save!
    end
  end

  def facebook
    @facebook ||= Koala::Facebook::API.new(oauth_token)
  end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    unless current_user == User.find(1)
      redirect_to root_url
    end
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show

    #redirect_to root_url
    #binding.pry
    unless current_user.id == params[:id].to_i
      redirect_to root_url
    end
  end

  # GET /users/new
  def new
    # @user = User.new
    redirect_to root_url
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<center>
<h3>Admin Page - Users</h3>
<% @users.each do |user| %>
  <h2> <%= link_to user.name, user %> </h2>
<% end %>
<br>
<br>
<br>
</center>

app/views/users/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<center>
<div class="user-show">
  <h3><%= @user.name %></h3>
  <br>
  <% if @user.questions.length == 0 %>
    <h2>Looks like you haven't asked any questions yet!</h2>
    <h2><span><%= link_to 'I want to ask my first question!', new_question_path %></span></h2>
    <h6>&hearts;</h6>
  <% elsif @user.questions.length == 1 %>
    <h2>You've asked <%= @user.questions.length %> question!</h2>
    <h2><span><%= link_to 'I want to ask another question!', new_question_path %></span></h2>
    <br>
  <% else %>
    <h2>You've asked <%= @user.questions.length %> questions!</h2>
    <h2><span><%= link_to 'I want to ask another question!', new_question_path %></span></h2>
    <br>
  <% end %>
  <% @user.questions.each do |question| %>
    <h2><%=link_to question.title, question %></h2>
    <h4><%= question.content %></h4> 
    <div class="dash-answers">
    <% if question.answers.length == 1 %>
      <h4><%= question.answers.length %> answer</h4>
    <% elsif question.answers.length > 1 %>
      <h4><%= question.answers.length %> answers</h4>
    <% else %>
      <h4>0 answers</h4>
    <% end %>
    </div>
    <% question.answers.each do |answer| %>
      <h4><strong><%= answer.user.name %>:</strong> <%= answer.content %></h4>
    <% end %>
    <p><%= link_to 'Edit', edit_question_path(question) %> | 
    <%= link_to 'Delete', question, method: :delete, data: { confirm: 'Are you sure?' } %></p>
    <h4>&hearts;</h4>
  <% end %>
  <br>
  <br>
  <br>
</div>
</center>