config/routes.rb
Rails.application.routes.draw do
  root 'application#index'

  get '/auth/facebook', as: "facebook_login"

  match 'auth/facebook/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]

  get 'logout' => 'sessions#destroy', :as => :logout

  
  resources :sessions
  resources :users, :only => [:new, :show, :index]
  resources :tags, :only => [:show, :index]
  
  resources :questions do 
    resources :answers, :only => [:new, :create, :destroy] # ADDED DESTROY
  end

  get "/:page" => "static#show"
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  
  has_many :question_tags
  has_many :questions, through: :question_tags

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tag = Tag.find(params[:id])
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/index.html.erb
<center>
<div class="tags-header">
  <h3>Categories</h3>
  <h2>View questions by category.</h2>
  <br>
</div>
<div class="tags-body">
  <p>
    <% @tags.each do |tag| %>
       <%= link_to tag.name, tag %>         
    <% end %>
  </p>
</div>
<br>
<br>
<br>
<br>
</center>

app/views/tags/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<center>
<div class="topic-header">
  <h3> <%= @tag.name %> </h3>
  <h2>The following questions relate to <%= @tag.name %>.</h2>
  <% if @tag.questions.empty? %>
    <h4>Sorry! There are no questions related to <%= @tag.name %> yet! Be the first!</h4>
  <% else %>
    <% @tag.questions.reverse.each do |question| %>
      <h2><%= link_to question.title, question_path(question) %></h2>
      <h4>Asked by <img src="<%= question.user.image %>" height="50"> <%= question.user.name %> </h4>
      <% if question.answers.length == 1 %>
        <h4><%= question.answers.length %> answer</h4>
      <% else %>
        <h4><%= question.answers.length %> answers</h4>
      <% end %>
      <h4>&hearts;</h4>  
    <% end %>
  <% end %>
</div>
<p><%= link_to 'Back', tags_path %></p>
<br>
<br>
<br>
</center>