config/routes.rb
Rails.application.routes.draw do
  root 'application#index'

  get '/auth/facebook', as: "facebook_login"

  match 'auth/facebook/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]

  get 'logout' => 'sessions#destroy', :as => :logout

  
  resources :sessions
  resources :users, :only => [:new, :show, :index]
  resources :tags, :only => [:show, :index]
  
  resources :questions do 
    resources :answers, :only => [:new, :create, :destroy] # ADDED DESTROY
  end

  get "/:page" => "static#show"
end

app/views/layouts/_footer.html.erb
<center>
<footer>
  <h4>&copy; 2014 <a href="http://iheartny.us" target="_blank">iheartny.us</a> &hearts;</h4>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-53201216-1', 'auto');
    ga('send', 'pageview');

  </script>
</footer>
</center>

app/views/layouts/_header.html.erb
<nav>
<div class="navbar navbar-default navbar-fixed-top">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a href="/" class="navbar-brand">I<span>&hearts;</span>NY</a>
  </div>
  <div class="navbar-collapse collapse navbar-responsive-collapse">
    <ul class="nav navbar-nav">
      <li class="active"></li>
      <li><%= link_to "Learn More", "/about" %></li> 
      <% if current_user %>
        <li><%= link_to "Ask a Question", new_question_path %></li>
        <li><%= link_to 'Browse Questions', questions_path %></li>
        <li><%= link_to 'Browse Categories', tags_path %></li>
      <% else %>
        <li><%= link_to 'Browse Questions', questions_path %></li>
        <li><%= link_to 'Browse Categories', tags_path %></li>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
    <% if current_user %>
      <li><%= link_to "Dashboard", current_user %></li>
      <li><a>Hey, <%= current_user.name.split(" ")[0] %>!</a></li>
      <li><img src="<%= current_user.image %>"></li>
      <li><%= link_to "Log Out", logout_path %></li>
    <% else %>
      <li><%= link_to "Log in with Facebook", facebook_login_path %></li>
    <% end %>
    </ul>
  </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IheartNY</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  <%= favicon_link_tag '/favicon.ico' %>
  <meta name="keywords" content="Koren Leslie Cohen, The Flatiron School, Flatiron School, New York City, NYC, Manhattan, New York guidebook"/>
  <meta name="description" content="IheartNY - Your guide to everything cool in New York City. Created by Koren Leslie Cohen.">
  <title>IheartNY - Your guide to everything cool in New York City.</title>
</head>
<body>
  <div id="container">
    <%= render 'layouts/header' %>
    <%= yield %>
  <footer>
    <%= render "layouts/footer" %>
  </footer>
  </div>
</body>
</html>